### ISSUE TITLE
How to map fields with fieldname as attribute

### ISSUE THREAD

**Issue by evallgar** [eye3/nkit4nodejs#2]
Hi,

I have an XML doc that looks like this:

**This is what I have**
````xml
<?xml version="1.0" encoding="UTF-8"?>
    <GTSResponse>
        <Record>
            <Field name="TITLE">Empire Burlesque</Field>
            <Field name="ARTIST">Bob Dylan</Field>
            <Field name="COUNTRY">USA</Field>
            <Field name="COMPANY">Columbia</Field>
            <Field name="PRICE">10.90</Field>
            <Field name="YEAR">1985</Field>
        </Record>
        <Record>
            <Field name="TITLE">Hide your heart</Field>
            <Field name="ARTIST">Bonnie Tyler</Field>
            <Field name="COUNTRY">UK</Field>
            <Field name="COMPANY">CBS Records</Field>
            <Field name="PRICE">9.90</Field>
            <Field name="YEAR">1988</Field>
        </Record>
    </GTSResponse>
````

**This is what I need**
````json
{ records: [ { "TITLE":"Empire Burlesque", "ARTIST":"Bob Dylan", "COUNTRY":"USA", "COMPANY":"Columbia","PRICE":"10.90", "YEAR":"1985"},{"TITLE":"Hide your heart", "ARTIST":"Bonnie Tyler", "COUNTRY":"UK", "COMPANY":"CBS Records","PRICE":"9.90","YEAR":"1988"} ] }
````

**This is what I'm getting right now**
````js
[ [ { field: 'Empire Burlesque' },
    { field: 'Bob Dylan' },
    { field: 'USA' },
    { field: 'Columbia' },
    { field: '10.90' },
    { field: '1985' } ],
  [ { field: 'Hide your heart' },
    { field: 'Bonnie Tyler' },
    { field: 'UK' },
    { field: 'CBS Records' },
    { field: '9.90' },
    { field: '1988' } ] ]
````

**This is how i'm getting it**
````js
mapping = ["/Record", ["/Field", {"/ -> field": "string"} ]];
````

What do I need to do to get what I need? Hope you can help me achieve it ... thanks!

**Comment by eye3** [comment]
Hi, @evallgar !

I added this functionality to project and pushed it to github. Can you test? Try following mapping:
["/Record", {"/Field -> \@name": "string"} ]

Here object key definition "/Field -> \@name" contain key alias '\@name', which mean that module will use 'name' attribute values for keys.

I wanted to add this case to project for a long time, but my laziness... Thank you for waking me:)

**Comment by evallgar** [comment]
Hey! thanks for your help. I really appreciate it ...

Im struggling right now with a gyp error ... hope to get this solved tonight.

````js
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make: *** [Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic.o] Error 4
make: *** Waiting for unfinished jobs....
make: Leaving directory `/srv/node_modules/nkit4nodejs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-79-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "build" "--release"
gyp ERR! cwd /srv/node_modules/nkit4nodejs
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
````

I will let you know how it goes ... Thanks again!!

**Comment by eye3** [comment]
Please, give me information about your platform, its version and version of gcc. I will try to see what happens. I don't promise, that will solve problem today, may be on next holidays: I'm very busy on my job. Up to this moment I compiled projects on Ubuntu 2012, Windows 7 and later version of Mac & Xcode. May be there are problems on new compilers on new Linux'es

**Comment by eye3** [comment]
I had seen gcc version in your message, so let me know, what OS you are using, Ubuntu, CentOS or something else? And its version.

**Comment by evallgar** [comment]
I'm using ubuntu 14.04

**Comment by evallgar** [comment]
````unix
Linux ubuntu-512mb-nyc2-gdtrack-02 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

x86_64

Linux version 3.13.0-79-generic (buildd@lcy01-24) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016

Ubuntu 14.04.4 LTS \n \l
````

**Comment by eye3** [comment]
I found Ubuntu 2014.04 on my VirtualBox. Module compiles with nodejs 0.10.17

$ uname -a
Linux bdarchiev-u1 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

$ node --version
v0.10.17

$ npm install git+https://github.com/eye3/nkit4nodejs.git
/
> nkit4nodejs@2.4.1 install /home/bdarchiev/tmp/node_modules/nkit4nodejs
> node-gyp rebuild

make: Entering directory `/home/bdarchiev/tmp/node_modules/nkit4nodejs/build'
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/nkit/deps/nkit/src/constants.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/tools.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_json.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_path.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_table.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_table_index_comparators.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_xml.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/logger/rotate_logger.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/encoding/transcode.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/xml/xml2var.o
  CXX(target) Release/obj.target/nkit/deps/nkit/3rd/netbsd/strptime.o
  AR(target) Release/obj.target/deps/libnkit.a
  COPY Release/libnkit.a
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_lex.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_encode.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_parser.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_version.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_alloc.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_buf.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_tree.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_gen.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl.o
  AR(target) Release/obj.target/deps/libyajl.a
  COPY Release/libyajl.a
  CXX(target) Release/obj.target/nkit4nodejs/src/nkit4nodejs_module.o
  CXX(target) Release/obj.target/nkit4nodejs/src/xml2var_builder_wrapper.o
  CXX(target) Release/obj.target/nkit4nodejs/src/anyxml2var_builder_wrapper.o
  CXX(target) Release/obj.target/nkit4nodejs/src/v8_var_policy.o
  SOLINK_MODULE(target) Release/obj.target/nkit4nodejs.node
  SOLINK_MODULE(target) Release/obj.target/nkit4nodejs.node: Finished
  COPY Release/nkit4nodejs.node
make: Leaving directory `/home/bdarchiev/tmp/node_modules/nkit4nodejs/build'
nkit4nodejs@2.4.1 node_modules/nkit4nodejs

**Comment by eye3** [comment]
I installed Ubuntu 2016.04. Module compiles on it too.

$ uname -a
Linux bdarchiev-2016 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ gcc --version
gcc (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413

$ node --version
v0.10.45

$ npm install git+https://github.com/eye3/nkit4nodejs.git
|
> nkit4nodejs@2.4.1 install /home/bdarchiev/tmp/node_modules/nkit4nodejs
> node-gyp rebuild

make: Entering directory '/home/bdarchiev/tmp/node_modules/nkit4nodejs/build'
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/nkit/deps/nkit/src/constants.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/tools.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_json.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_path.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_table.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_table_index_comparators.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_xml.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/logger/rotate_logger.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/encoding/transcode.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/xml/xml2var.o
  CXX(target) Release/obj.target/nkit/deps/nkit/3rd/netbsd/strptime.o
  AR(target) Release/obj.target/deps/libnkit.a
  COPY Release/libnkit.a
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_lex.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_encode.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_parser.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_version.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_alloc.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_buf.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_tree.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_gen.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl.o
  AR(target) Release/obj.target/deps/libyajl.a
  COPY Release/libyajl.a
  CXX(target) Release/obj.target/nkit4nodejs/src/nkit4nodejs_module.o
  CXX(target) Release/obj.target/nkit4nodejs/src/xml2var_builder_wrapper.o
  CXX(target) Release/obj.target/nkit4nodejs/src/anyxml2var_builder_wrapper.o
  CXX(target) Release/obj.target/nkit4nodejs/src/v8_var_policy.o
  SOLINK_MODULE(target) Release/obj.target/nkit4nodejs.node
  COPY Release/nkit4nodejs.node
make: Leaving directory '/home/bdarchiev/tmp/node_modules/nkit4nodejs/build'
nkit4nodejs@2.4.1 node_modules/nkit4nodejs

**Comment by evallgar** [comment]
````unix
root@ubuntu-512mb-nyc2-gdtrack-02:/srv# npm install git+https://github.com/eye3/nkit4nodejs.git
npm ERR! git Appears to be a git repo or submodule.
npm ERR! git     /srv/node_modules/nkit4nodejs
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "git+https://github.com/eye3/nkit4nodejs.git"
npm ERR! cwd /srv
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /srv/node_modules/nkit4nodejs
npm ERR! code EISGIT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/npm-debug.log
npm ERR! not ok code 0
root@ubuntu-512mb-nyc2-gdtrack-02:/srv#
````

**Comment by evallgar** [comment]
Now this error ...

````unix
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-79-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /srv/node_modules/nkit4nodejs
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0
````

**Comment by eye3** [comment]
May be something wrong with you node & node-gyp & npm installation or their's version compatibility? Unfortunately, I'm not node & npm expert. Have no idea...

**Comment by evallgar** [comment]
Thanks for your help ... I will figure it out somehow ... Once I get it done ... will let you know how did it go with your change ... thanks!!

**Comment by evallgar** [comment]
good news! I figured it out ...

Whenever something goes wrong for a long period of time I begin "fix'n" stupid things ...

I noticed I had not set locale settings, so I went to /etc/environment and set my locale settings, logged out and then ...

````unix
root@ubuntu-512mb-nyc2-gdtrack-02:~/node_modules# npm install git+https://github.com/eye3/nkit4nodejs.git

> nkit4nodejs@2.4.1 install /root/node_modules/nkit4nodejs
> node-gyp rebuild

make: Entering directory `/root/node_modules/nkit4nodejs/build'
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/nkit/deps/nkit/src/constants.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/tools.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_json.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_path.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_table.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_table_index_comparators.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_xml.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/logger/rotate_logger.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/encoding/transcode.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/xml/xml2var.o
  CXX(target) Release/obj.target/nkit/deps/nkit/3rd/netbsd/strptime.o
  AR(target) Release/obj.target/deps/libnkit.a
  COPY Release/libnkit.a
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_lex.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_encode.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_parser.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_version.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_alloc.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_buf.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_tree.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_gen.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl.o
  AR(target) Release/obj.target/deps/libyajl.a
  COPY Release/libyajl.a
  CXX(target) Release/obj.target/nkit4nodejs/src/nkit4nodejs_module.o
  CXX(target) Release/obj.target/nkit4nodejs/src/xml2var_builder_wrapper.o
  CXX(target) Release/obj.target/nkit4nodejs/src/anyxml2var_builder_wrapper.o
  CXX(target) Release/obj.target/nkit4nodejs/src/v8_var_policy.o
  SOLINK_MODULE(target) Release/obj.target/nkit4nodejs.node
  SOLINK_MODULE(target) Release/obj.target/nkit4nodejs.node: Finished
  COPY Release/nkit4nodejs.node
make: Leaving directory `/root/node_modules/nkit4nodejs/build'
nkit4nodejs@2.4.1 nkit4nodejs
````

Now, I will try your PR and let you know results ... Thanks!

**Comment by evallgar** [comment]
OMG!! It works ... Thanks a lot, I really appreciate your efforts !! So happy ... thanks!!

````js
[ { accountID: '****',
    deviceID: '****_001',
    timestamp: '1463064027',
    statusCode: '0xF112',
    latitude: '20.907305',
    longitude: '-101.38247',
    address: 'Calle Bugambilia, Guanajuato, México',
    odometerKM: '7094.97',
    odometerOffsetKM: '2052.9',
    creationTime: '1463063969',
    creationMillis: '1463063969066',
    streetAddress: 'Calle Bugambilia',
    city: '',
    stateProvince: 'Gto.',
    postalCode: '',
    country: 'MX',
    satelliteCount: '11',
    signalStrength: '27.0',
    fuelLevel: '0.361075658581048',
    fuelLevel2: '0.0' },
  { accountID: '****',
    deviceID: '****_001',
    timestamp: '1463064500',
    statusCode: '0xF403',
    latitude: '20.90546',
    longitude: '-101.387395',
    address: 'Unnamed Road, Guanajuato, México',
    odometerKM: '7096.0',
    odometerOffsetKM: '2052.9',
    creationTime: '1463064440',
    creationMillis: '1463064440415',
    streetAddress: 'Unnamed Road',
    city: '',
    stateProvince: 'Gto.',
    postalCode: '',
    country: 'MX',
    satelliteCount: '11',
    signalStrength: '31.0',
    fuelLevel: '0.361075658581048',
    fuelLevel2: '0.0' },
  { accountID: '****',
    deviceID: '****_001',
    timestamp: '1463064772',
    statusCode: '0xF020',
    latitude: '20.90546',
    longitude: '-101.387395',
    address: 'Mexico 45, Silao, Guanajuato, México',
    odometerKM: '7096.0',
    odometerOffsetKM: '2052.9',
    creationTime: '1463064714',
    creationMillis: '1463064714612',
    streetAddress: 'Mexico 45',
    city: 'Silao',
    stateProvince: 'Guanajuato',
    postalCode: '',
    country: 'MX',
    satelliteCount: '9',
    signalStrength: '31.0',
    fuelLevel: '0.361075658581048',
    fuelLevel2: '0.0' },
  { accountID: '****',
    deviceID: '****_001',
    timestamp: '1463064772',
    statusCode: '0xF401',
    latitude: '20.90546',
    longitude: '-101.387395',
    address: 'Mexico 45, Silao, Guanajuato, México',
    odometerKM: '7096.0',
    odometerOffsetKM: '2052.9',
    creationTime: '1463064711',
    creationMillis: '1463064711832',
    streetAddress: 'Mexico 45',
    city: 'Silao',
    stateProvince: 'Guanajuato',
    postalCode: '',
    country: 'MX',
    satelliteCount: '9',
    signalStrength: '31.0',
    fuelLevel: '0.361075658581048',
    fuelLevel2: '0.0' },
  { accountID: '****',
    deviceID: '****_001',
    timestamp: '1463064896',
    statusCode: '0xF403',
    latitude: '20.904985',
    longitude: '-101.387575',
    address: 'Mexico 45, Silao, Guanajuato, México',
    odometerKM: '7096.1',
    odometerOffsetKM: '2052.9',
    creationTime: '1463064835',
    creationMillis: '1463064835492',
    streetAddress: 'Mexico 45',
    city: 'Silao',
    stateProvince: 'Guanajuato',
    postalCode: '',
    country: 'MX',
    satelliteCount: '11',
    signalStrength: '30.0',
    fuelLevel: '0.361075658581048',
    fuelLevel2: '0.0' } ]
````

**Comment by eye3** [comment]
I'm using python virtualenv to make "sandboxes" for different versions of programs, modules, packages, libraries. I'm not using systemwide installed node, npm. May be for this reason I haven't seen such problems. Try look closer to virtualenv.

**Comment by eye3** [comment]
I'm happy for you. Good luck!
